//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitDashboard.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockOptions
    {
        public int Id { get; set; }
        public string ContentBlock { get; set; }
        public string TypeBlock { get; set; }
    }
}
